version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.simple
    container_name: stable_crm_app
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/stable_crm_prod
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - PHX_HOST=${PHX_HOST}
      - VK_ID_CLIENT_ID=${VK_ID_CLIENT_ID}
      - VK_ID_CLIENT_SECRET=${VK_ID_CLIENT_SECRET}
      - VK_ID_REDIRECT_URI=${VK_ID_REDIRECT_URI}
    ports:
      - "4000:4000"
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: stable_crm_postgres
    environment:
      POSTGRES_DB: stable_crm_prod
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: stable_crm_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
